# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('xpath-routing', ['internet'])
    module.source = [
        'model/ipv4-xpath-routing.cc',
        'helper/ipv4-xpath-routing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('xpath-routing')
    module_test.source = [
        'test/xpath-routing-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'xpath-routing'
    headers.source = [
        'model/ipv4-xpath-routing.h',
        'helper/ipv4-xpath-routing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

