# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ipv4-conga-routing-example', ['conga-routing'])
    obj.source = 'ipv4-conga-routing-example.cc'

