# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('congestion-probing', ['core', 'internet', 'xpath-routing'])
    module.source = [
        'model/congestion-probing.cc',
        'model/congestion-probing-tag.cc',
        'helper/congestion-probing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('congestion-probing')
    module_test.source = [
        'test/congestion-probing-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'congestion-probing'
    headers.source = [
        'model/congestion-probing.h',
        'model/congestion-probing-tag.h',
        'helper/congestion-probing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

